### ISSUE TITLE
插件获取图片显示不了

### ISSUE THREAD

**Issue by FlickerMi** [lizheming/dbm#3]
插件获取图片显示不了
域名：http://lab.eming.li
例如：http://lab.eming.li/dou/6952149.jpg
目测问题是出在七牛收回测试域名。

顺便请问作者是怎么拿到豆瓣的图片的？

**Comment by lizheming** [comment]
是的，七牛回收测试域名了。我都忘记了我还用七牛提供了这个服务了，我国庆处理下吧，感谢反馈。

**Comment by lizheming** [comment]
暂时存本地了，应该 OK 了
豆瓣有提供 API 服务，虽然目前开发者文档已经关了，不过接口还可以正常运行。例如 https://api.douban.com/v2/movie/subject/6952149
