### ISSUE TITLE
某些图片显示不了了

### ISSUE THREAD

**Issue by FlickerMi** [lizheming/dbm#4]
例如：http://lab.eming.li/dou/27110296.jpg
请问还能提供服务吗？

**Comment by lizheming** [comment]
好了，迁移了一次服务导致本地文件夹写的权限没了，已经恢复感谢反馈。

**Comment by FlickerMi** [comment]
@lizheming 个别影片的图片还是不会显示，比如：http://lab.eming.li/dou/3184479.jpg
对应影片页面：https://movie.douban.com/subject/3184479/

**Comment by lizheming** [comment]
这种是没数据吧，你这电影页面打开我直接提示404找不到。

**Comment by FlickerMi** [comment]
@lizheming 不好意思，我刚刚仔细看了下，这影片好像已经在豆瓣下线了。
因为我之前标记成已观看，所以我在登录后是能进入影片详情的，实际上未标记影片或未登录状态下直接搜索已经找不到该影片。谢谢您！
